make workflow pass
thinc-org/open-reg-frontend-v2 pull request #2
Opened 2020-09-04 09:53 UTC by paphonb

2020-09-04 13:07 UTC, new5558 requested changes
staging กับ development มัน deploy ไปที่เดียวกันอะ

2020-09-04 13:07 UTC, new5558 commented on .github/workflows/staging.yml
> +    branches: [dev, cicd]
อย่าลืมลบ cicd ่กอน merge นะ

2020-09-04 13:28 UTC, paphonb commented on .github/workflows/staging.yml
> +    branches: [dev, cicd]
ทำไงให้มันไปคนละที่อ่าครับ

2020-09-04 14:03 UTC, new5558 approved these changes

2020-09-06 10:05 UTC, saenyakorn approved these changes

2020-09-06 10:05 UTC, merged